# The name of the binary file generated by this makefile.
FIRMWARE = firmware_makefile.bin

# Kick off a remote compile, saving it to $(FIRMWARE).
library:
	particle compile firmware/ --saveTo $(FIRMWARE)

example:
	particle compile firmware/examples/ --saveTo $(FIRMWARE)

# Delete previously-compiled binary, if it exsts.
clean:
	rm -f $(FIRMWARE)

# Flash the generated binary to a given $(DEVICE), or --usb if no device
# has been specified.
flash: clean online
ifeq ($(DEVICE),)
	particle flash --usb $(FIRMWARE)
endif
	particle flash $(DEVICE) $(FIRMWARE)

flash-example: clean example
ifeq ($(DEVICE),)
	particle flash --usb $(FIRMWARE)
endif
	particle flash $(DEVICE) $(FIRMWARE)
